version: '3.10'
services:
  web:
    build: .
    container_name: django_web
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
      
  nginx:
    image: nginx:latest
    container_name: django_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web

volumes:
  static_volume:
