# Generated by Django 5.1.6 on 2025-03-02 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='スコア種類')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_score',
        ),
        migrations.AddField(
            model_name='score',
            name='score_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.scoretype', verbose_name='スコア種類'),
        ),
        migrations.CreateModel(
            name='TargetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_score', models.IntegerField(default=3000)),
                ('score_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.scoretype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'score_type')},
            },
        ),
    ]
