# Generated by Django 5.1.6 on 2025-03-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_scoretype_remove_userprofile_target_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.scoretype', verbose_name='スコア種類'),
        ),
    ]
